#encapsulamiento

class CuentaBancaria:
    def __init__(self, titular, saldo, tipo_cuenta):
        self.__titular = titular  #PRIVADO con Encapsulamiento __ para indicar que es privado
        self.__saldo = saldo
        self.__tipo_cuenta = tipo_cuenta

    def consultar(self):
            print(f"El saldo de la cuenta de {self.__titular} ({self.__tipo_cuenta}) es: {self.__saldo}")
            return self.__saldo 
            
        
    def depositar(self, cantidad):
            if cantidad > 0:
                self.__saldo += cantidad
                print(f"Depósito exitoso. Nuevo saldo: {self.__saldo}")
            else:
                print("Cantidad inválida. El depósito debe ser mayor a cero.")
                
    def retirar(self, cantidad):
            if cantidad > 0 and cantidad <= self.__saldo:
                self.__saldo -= cantidad
                print(f"Retiro exitoso. Nuevo saldo: {self.__saldo}")
            else:
                print("Cantidad inválida o saldo insuficiente para el retiro.")
                
    def eliminar_cuenta(self):
            self.__titular = None
            self.__saldo = 0
            print("Cuenta eliminada.")
            
cuenta1 = CuentaBancaria("Juan", 1000, "Ahorros")

# cuenta1.tipo_cuenta = "Corriente"
cuenta1.consultar()
# cuenta1.retirar(500)
# cuenta1.consultar()
# cuenta1.depositar(200)
# cuenta1.consultar()

# cuenta1.eliminar_cuenta()
# cuenta1.consultar()

#GET SERIA TRAER INFORMACION DE UN ATRIBUTO
#SET SERIA MODIFICAR EL VALOR DE UN ATRIBUTO

#POO = Programación Orientada a Objetos
#ENCAPSULAMIENTO = OCULTAR LOS DETALLES DE IMPLEMENTACION DE UNA CLASE, PROTEGIENDO LOS ATRIBUTOS Y METODOS DE ACCESOS EXTERNOS, PERMITIENDO CONTROLAR EL ACCESO A LOS DATOS Y MANTENER LA INTEGRIDAD DE LA INFORMACION.
#HERENCIA = PERMITE CREAR NUEVAS CLASES BASADAS EN CLASES EXISTENTES, HEREDANDO SUS ATRIBUTOS Y METODOS, PERMITIENDO REUTILIZAR CODIGO Y EXTENDER FUNCIONALIDADES.
#POLIMORFISMO = PERMITE QUE LOS OBJETOS DE DIFERENTES CLASES SEAN TRATADOS COMO OBJETOS DE UNA CLASE COMUN, PERMITIENDO QUE LOS METODOS SE COMPORTEN DE MANERA DIFERENTE SEGUN EL TIPO DE OBJETO QUE LOS INVOQUE, FACILITANDO LA FLEXIBILIDAD Y LA EXTENSIBILIDAD DEL CODIGO.
#ABSTRACCION = PERMITE REPRESENTAR CONCEPTOS COMPLEJOS DE MANERA SIMPLIFICADA, OCULTANDO LOS DETALLES DE IMPLEMENTACION Y MOSTRANDO SOLO LA FUNCIONALIDAD ESENCIAL, FACILITANDO LA COMPRENSION Y EL USO DE LOS OBJETOS.

#SOLID = PRINCIPIOS DE DISEÑO DE SOFTWARE QUE PROMUEVEN LA CREACION DE CODIGO LIMPIO, MANTENIBLE Y ESCALABLE, INCLUYENDO PRINCIPIOS COMO LA RESPONSABILIDAD UNICA, ABIERTO/CERRADO, LISKOV, INTERFAZ SEGREGADA Y DEPENDENCIA INVERSION.
# SOLID = SINGLE RESPONSIBILITY, 
# OPEN/CLOSED, 
# LISKOV SUBSTITUTION, 
# INTERFACE SEGREGATION, 
# DEPENDENCY INVERSION

#SINGLE RESPONSIBILITY = CADA CLASE DEBE TENER UNA SOLA RESPONSABILIDAD O MOTIVO PARA CAMBIAR, LO QUE FACILITA LA MANTENIBILIDAD Y LA COMPRENSION DEL CODIGO.
#OPEN/CLOSED = LAS ENTIDADES DE SOFTWARE DEBEN ESTAR ABIERTAS PARA LA EXTENSION PERO CERRADAS PARA LA MODIFICACION, LO QUE PERMITE AGREGAR NUEVA FUNCIONALIDAD SIN MODIFICAR EL CODIGO EXISTENTE.
#LISKOV SUBSTITUTION = LOS OBJETOS DE UNA CLASE DERIVADA DEBEN PODER SUSTITUIR A LOS OBJETOS DE LA CLASE BASE SIN AFECTAR EL COMPORTAMIENTO DEL PROGRAMA, LO QUE GARANTIZA LA CORRECTA HERENCIA Y POLIMORFISMO.
#INTERFACE SEGREGATION = LOS CLIENTES NO DEBEN VERSE OBLIGADOS A DEPENDER DE INTERFACES QUE NO UTILIZAN, LO QUE PROMUEVE LA CREACION DE INTERFACES ESPECIFICAS Y EVITA LA SOBRECARGA DE FUNCIONALIDAD.
#DEPENDENCY INVERSION = LOS MÓDULOS DE ALTO NIVEL NO DEBEN DEPENDER DE LOS MÓDULOS DE BAJO NIVEL, SINO QUE AMBOS DEBEN DEPENDER DE ABSTRACCIONES, LO QUE FOMENTA LA FLEXIBILIDAD Y LA INDEPENDENCIA ENTRE LOS COMPONENTES DEL SOFTWARE.